### ISSUE TITLE
Hiding the "/post" part

### ISSUE THREAD

**Issue by braimee** [digitalcraftsman/hugo-strata-theme#12]
Hi there,

I'm trying to migrate my blog from Ghost to Hugo, and I'd love to use your theme.  The default "blog" link in the sidebar make the url be http://site.com/post/name-of-post.  My current URL structure is http://site.com/name-of-post.  Is there a way I can change the config somehow so that my URLs don't get broken when I move from Ghost to Hugo?

Brian

**Comment by digitalcraftsman** [comment]
Hello @braimee,

Hugo has a feature called [permalinks](https://gohugo.io/extras/permalinks/) that allows you to rewrite the url.

Just add the following snippet to your config file:

```
[permalinks]
	post = "/:title"
```

**Comment by braimee** [comment]
That worked like a champ, thanks!
