### ISSUE TITLE
"Hide" pages from blog entries

### ISSUE THREAD

**Issue by braimee** [digitalcraftsman/hugo-strata-theme#13]
Hi there,

In my existing Ghost blog I have several entries like /about and /contact with static content.  I'd like to keep these in tact when I migrate to Hugo and use your theme, but I'd _also_ like to "hide" them from popping up in the rest of the blog entries when people click "Blog" on the left.  Is there a way to designate these /about, /contact, /resume .md files in such a way that they're still available as static posts but NOT lumped in with other blog entries?

Thanks,
Brian

**Comment by digitalcraftsman** [comment]
Hello again,

the template that renders the page `example.com/post/` will only list pages that are part of this subfolder in your content directory. I don't assume you save your about and resume pages there as well.

```
content/
    post/      // only content of this subfolder will be listed at /post/
        foo.md
        bar.md
    about.md
    resume.md
```

**Comment by braimee** [comment]
Awesome - I just pulled the static posts back into /content and linked them directly from main side menu.  Thanks!
