### ISSUE TITLE
Adding a "recent blog entries" to front page?

### ISSUE THREAD

**Issue by braimee** [digitalcraftsman/hugo-strata-theme#14]
Hi again,

I like how customizable the landing page is.  I'm wondering if, below "recent projects" is there a way to have a header called "Recent blog posts" that would then list, say, the latest 3-5 entries that people would see if they clicked "Blog" from the left hand menu?

Thanks,
Brian

**Comment by braimee** [comment]
Hey I know it took me forever to w/b but just wanted to say THANKS for quickly resolving the bundle of issues I submitted in Sept.  The only one I had a remaining question on was this one.  Where would I be able to put a small header above the 5 recent posts to say something like "Recent Posts" ?

<img width="773" alt="recentpost" src="https://cloud.githubusercontent.com/assets/17596787/20034874/c457ce24-a39c-11e6-8d0d-75b3d90a0bc0.png">


Thanks,
Brian

**Comment by digitalcraftsman** [comment]
> Where would I be able to put a small header above the 5 recent posts to say something like "Recent Posts" ?

Perhaps you didn't added the [new parameters](https://github.com/digitalcraftsman/hugo-strata-theme/blob/master/exampleSite/config.toml#L96) to your config file. Just set the `title` in the `recentposts` block.

**Comment by braimee** [comment]
That did it - thanks!
