### ISSUE TITLE
Have "portfolio" thumbnail just go to an http link rather than show a larger image?

### ISSUE THREAD

**Issue by braimee** [digitalcraftsman/hugo-strata-theme#15]
Hi,

Is there a config change I can make such that one of my portfolio thumbnails just links to another http page, rather than display a larger image?

Thanks,
Brian

**Comment by braimee** [comment]
Nudge?  :-)

**Comment by FISHunderscore** [comment]
I'd like this feature as well 👍

**Comment by samrichca** [comment]
1. Make your portfolio pages in content/portfolio/.
2. In static/js/main.js, change `.work-item a.image` to `.work-item a.js-image`.
3. In layouts/_partials/portfolio.html, replace the anchor tag with this:

```
{{ if isset . "link" }}
    <a href="{{ $.Site.BaseURL }}portfolio/{{ .link }}" class="image fit thumb"><img src="{{ $.Site.BaseURL }}images/{{ .thumb }}" alt="" /></a>
{{ else }}
    <a href="{{ $.Site.BaseURL }}images/{{ .image }}" class="image fit thumb js-image"><img src="{{ $.Site.BaseURL }}images/{{ .thumb }}" alt="" /></a>
{{ end }}
```

4. In config.toml, add a "link" line to your portfolio config if you want it to go to another page. The string is the filename of the page you created.

```
[[params.portfolio.gallery]]
      image = "fulls/04.jpg"
      thumb = "thumbs/04.jpg"
      title = "Lorem ipsum dolor."
      description = "Lorem ipsum dolor sit amet."
      link = "04"
```

**Comment by m4k5** [comment]
@samrichca for me your solution doesn't work. I pulled your code with an exampleSite, but on portfolios images with links, they are stuck at loading circle.

**Comment by braimee** [comment]
Closing as I've moved to a new platform.

**Comment by m4k5** [comment]
@braimee which one ;)?

**Comment by braimee** [comment]
I'm doing hosted Ghost.
