### ISSUE TITLE
where can I find "_internal/disqus.html" page

### ISSUE THREAD

**Issue by fredia** [digitalcraftsman/hugo-strata-theme#21]
hello,I want to use duoshuo to instead disqus,because I am in China,the disqus website can not open.
so,I want to change **single.html**, but it doesn't work.
Can you help me

**Comment by digitalcraftsman** [comment]
Hello @fredia,

Hugo itself is shipped with templates for common usecases, like the integration of [comments]. Such templates are prefixed with "_internal" in their path. Just replace `{{ template "_internal/disqus.html" . }}
` inside the template with the code of Duashuo.

**Comment by fredia** [comment]
I've done it, thank you very much!!O(∩_∩)O~~ I built a new duoshuo.html in partials,and replaced "{{ template "_internal/disqus.html" . }}" by"{{ partial "duoshuo.html" . }}" 
By the way,this themes is very beautiful.Nice going!
Thank you once again for your good job!

**Comment by digitalcraftsman** [comment]
> By the way,this themes is very beautiful.Nice going!

Thank you.

Since this issue seems to be resolved I'll close this issue.

**Comment by paskal** [comment]
Answering the original question (which I was wondering myself): [temmplate_embedded.go](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/template_embedded.go) is source code for all _internal html pages.
