### ISSUE TITLE
Is there a LESS or SASS version of the CSS file main.css ?

### ISSUE THREAD

**Issue by HadrienPierart** [digitalcraftsman/hugo-strata-theme#34]
I must admit that the 4k lines css file if kind of scary to edit... Is there a -not- preprocessed version of this file, maybe split into multiple file to make it easier to edit ?

Cheers !

PS : Awesome theme BTW, thx !

**Comment by digitalcraftsman** [comment]
Hello @HadrienPierart,

have a look at the original theme at https://html5up.net. The ZIP-file for the theme contains the SASS version of the the stylesheets.

Regards
Digitalcraftsman
