### ISSUE TITLE
favicon.ico

### ISSUE THREAD

**Issue by sanati** [digitalcraftsman/hugo-strata-theme#46]
Is it possible to put into this theme a favicon reference ( in config.toml)?

**Comment by m4k5** [comment]
@sanati you can just include your favicon.ico in static directory, so it would be available for browsers

**Comment by sanati** [comment]
Thanks, but i think a parameter must be in config.toml to let hugo to generate a proper html to display favicon.ico in browser, because this still does not work for me (a newbie)

**Comment by sanati** [comment]
Sorry, (my fault) its working! Thanks!

**Comment by Hanzei** [comment]
Can this issue be closed?
