### ISSUE TITLE
Older posts broken link

### ISSUE THREAD

**Issue by willis7** [digitalcraftsman/hugo-strata-theme#54]
I've been using this theme for a while and only now realised the "Older" button on the Blog page has an incorrect link in my implementation.

A live version you can see; https://sionwilliams.com/post/

If you scroll to the bottom and click older, you will see the issue.

**Comment by Programazing** [comment]
@willis7 

I've forked this repo and started working on updating it if you're interested in an actively developed theme:

https://github.com/Programazing/hugo-strata-theme-II

**Comment by willis7** [comment]
This was a base url config issue. Fixed.
