### ISSUE TITLE
Difficulty in deploying the site?

### ISSUE THREAD

**Issue by MoreThanLuck** [digitalcraftsman/hugo-strata-theme#60]
Hey there,

I used your theme to build a site I was happy with locally, and it looks exactly as intended on localhost. However, when I go to add it to a git repo and deploy on Netlify, it's not deploying correctly, instead copying all the content but not the styling.

I started a new Hugo site locally, cloned your theme into `themes/hugo-strata-theme`, deleted the git file from the theme folder, and after configuring how I intended and checking on localhost, initialized a new git repo in the home directory of the project. I then added all, made an initial commit, and linked to a repo. Github isn't pulling the blank directories of course, so the repo isn't the same as it looks locally. 

What steps should I take to correctly deploy this on netlify or github pages?

**Comment by Programazing** [comment]
@MoreThanLuck 

I've forked this repo and started working on updating it if you're interested in an actively developed theme:

https://github.com/Programazing/hugo-strata-theme-II

**Comment by MoreThanLuck** [comment]
I am, thank you! Will switch over soon.
