### ISSUE TITLE
Allow blog posts

### ISSUE THREAD

**Issue by haf** [digitalcraftsman/hugo-strata-theme#8]
Greetings,

Excellent port / theme.

It would be excellent if it allowed posts, out of the box :)

Cheers

**Comment by digitalcraftsman** [comment]
Hello @haf,

nice to hear that you like the theme. Initially, it was meant to be a single page website. It shouldn't be hard to expand it with blogging capabilities. I'm busy right now and don't have much time to implement it in the next time.

But I would appreciate any kinds of pull requests. The addtions should be hard to make:

Create at new template at `layouts/_defaults/` named `single.html`. This represents all single pages, e.g. a blog post. In general, it has the same structure as the `index.html` template. The about partial should be a good starting point for the content of the single pages. 

If you merge both, the `index.html` template and the `about.html` partial, you should have the basic setup for a blog. Finally, you could create a new partial for the homepage that lists your recent posts.

**Comment by digitalcraftsman** [comment]
@haf I added some blogging functions. Take a look at the [Changelog](https://github.com/digitalcraftsman/hugo-strata-theme/blob/master/CHANGELOG.md) and fetch the latest version.
